# Generated by Django 5.1.3 on 2024-12-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_brand_created_at_brand_created_by_brand_updated_at_and_more'),
        ('store', '0006_address_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='manager.productvariant'),
        ),
    ]
