# Generated by Django 5.1.3 on 2025-01-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_user_dob_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
