# Generated by Django 5.1.3 on 2025-01-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_approved', 'Returned'), ('return_rejected', 'Return Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
