# Generated by Django 5.1.3 on 2025-01-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
