# Generated by Django 5.1.3 on 2025-01-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_name',
            field=models.CharField(blank=True, default=None, max_length=75, null=True),
        ),
    ]
