# Generated by Django 5.1.3 on 2025-01-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_address_type_order_delivery_address_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
