# Generated by Django 5.1.3 on 2025-01-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_cart_applied_coupon_order_applied_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
