# Generated by Django 5.1.3 on 2024-12-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='name',
            new_name='color',
        ),
    ]
