# Generated by Django 5.1.3 on 2024-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_rename_color_productvariant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='connectivity',
            field=models.CharField(choices=[('wired', 'Wired'), ('wireless', 'Wireless'), ('multi', 'Multi-functional')], max_length=20),
        ),
    ]
