# Generated by Django 5.1.3 on 2024-12-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_type_product_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
    ]
