# Generated by Django 5.1.3 on 2025-01-14 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_offer_brand_alter_offer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_offers', to='manager.brand'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='manager.product'),
        ),
    ]
