# Generated by Django 5.1.3 on 2025-01-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_offer_created_at_alter_offer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(),
        ),
    ]
