# Generated by Django 5.1.3 on 2025-01-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_coupon_end_date_alter_coupon_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applied_to',
        ),
    ]
