# Generated by Django 5.1.3 on 2025-01-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_coupon_applied_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusage',
            name='status',
        ),
    ]
